# Generated by Django 4.1.7 on 2023-08-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_record_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
